title: "HMHI"
description: "Human-Machine Harmony for Infrastructure"
baseurl: ""
url: "https://hmhi-lab.github.io"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

markdown: kramdown
