title: "Human-Machine Harmony for Infrastructure (HMHI)"
email: youremail@cmu.edu
description: >- 
  A research lab at CMU exploring human-machine collaboration for smarter infrastructure systems.
baseurl: "/hmhi"
url: "https://hmhi-lab.github.io"
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

markdown: kramdown
