title: "Human-Machine Harmony for Infrastructure (HMHI)"
email: seongeup@andrew.cmu.edu
description: >- 
  A research lab at CMU exploring human-machine collaboration for smarter infrastructure systems.

baseurl: "/hmhi"
url: "https://hmhi-lab.github.io"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

markdown: kramdown
